
services:
  web:
    build: ./home_manager
    command: python /home_manager/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - ./home_manager/:/home_manager/
    ports:
      - 8000:8000
    env_file:
      - .env

  db:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  pg_data:
