
services:

  nginx:
    build:
      ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn home_manager.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
    expose:
      - 8000
    env_file:
      - ./.env.prod

  db:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod

volumes:
  pg_data: