
services:

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/django_app/web/staticfiles
      - media_volume:/home/django_app/web/media
    ports:
      - 1337:80
    depends_on:
      - web

  web:
    build:
      context: ./home_manager
      dockerfile: Dockerfile.prod
    command: gunicorn home_manager.wsgi:application --bind 0.0.0.0:8000 && python manage.py migrate --no-input && python manage.py collectstatic --no-input --clear
    volumes:
      - static_volume:/home/django_app/web/staticfiles
      - media_volume:/home/django_app/web/media
    depends_on:
      - db
    expose:
      - 8000
    env_file:
      - .env.prod

  cache:
    image: memcached:latest
    ports:
      - 11211:11211
    command:
      - '-m 128'

  db:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod

volumes:
  pg_data:
  static_volume:
  media_volume: