
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - memcached
    volumes:
      - .:/home_manager
    ports:
      - 8000:8000
    env_file:
      - ./.env
    networks:
      - django_app_network

  db:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - django_app_network

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
    command: [ "memcached" ]
    networks:
      - django_app_network


volumes:
  pg_data:

networks:
  django_app_network: