# Generated by Django 5.1 on 2024-08-18 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0005_rename_reminders_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryitem',
            name='is_checked',
        ),
    ]
