# Generated by Django 5.1 on 2024-08-19 02:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0006_remove_groceryitem_is_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='time_to_send',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
