#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

gunicorn home_manager.wsgi:application --bind 0.0.0.0:8000
python manage.py makemigrations --no-input
python manage.py migrate --no-input
python manage.py collectstatic --no-input --clear